### ISSUE TITLE
Error "Cannot read property 'startOffset' of undefined" w/ <svg xmlns:xlink="">

### ISSUE THREAD

**Issue by calvinjuarez** [ota-meshi/eslint-plugin-lodash-template#136]
When I extend `plugin:lodash-template/recommended-with-html`, I get an error on any template file that contains an SVG with an `xmlns:xlink` attribute or a `xml:space` attribute.  Note that this does **NOT** happen for `plugin:lodash-template/recommended` or `plugin:lodash-template/recommended-with-script`.

I'm trying to isolate which rule might be causing the problem.

**UPDATE:** Turning on _any_ of the rules listed under `recommended-with-html` will 'cause the issue.

###### template.ejs
```html
<svg xml:space="preserve"></svg>
```
###### .eslintrc.js
```js
module.exports = {
    'extends': [
        'plugin:lodash-template/recommended-with-html',
    ],
}
```
#### Expected Result
ESLint should pass without any issue.
#### Actual Result
ESLint errors with the following output.
```
Message:
    Cannot read property 'startOffset' of undefined
Occurred while linting /path/to/template.ejs:1
Details:
    currentNode: [object Object]
    domainEmitter: [object Object]
    domainThrown: false
```
#### Versions
eslint-plugin-lodash-template: 0.18.0
ESLint: 6.0.0 via gulp-eslint 6.0.0
npm: 6.14.5
Node: 12.14.0
OS: macOS 10.15.5
