### ISSUE TITLE
svg viewBox attribute throws "Cannot read property 'startOffset' of undefined"

### ISSUE THREAD

**Issue by calvinjuarez** [ota-meshi/eslint-plugin-lodash-template#139]
Looks like the camel casing is the problem here.  I'll try to create a PR.

###### template.ejs
```html
<svg viewBox="0 0 100 100"></svg>
```
###### .eslintrc.js
```js
module.exports = {
    'extends': [
        'plugin:lodash-template/recommended-with-html',
    ],
}
```
#### Expected Result
ESLint should pass without any issue.
#### Actual Result
ESLint errors with the following output.
```
Message:
    Cannot read property 'startOffset' of undefined
Occurred while linting /path/to/template.ejs:1
Details:
    currentNode: [object Object]
    domainEmitter: [object Object]
    domainThrown: false
```
#### Versions
eslint-plugin-lodash-template: 0.18.1
ESLint: 6.0.0 via gulp-eslint 6.0.0
npm: 6.14.5
Node: 12.14.0
OS: macOS 10.15.5
